steps:
  # Build the container image (build context is frontend dir when submitting from frontend/)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=${_API_URL}'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_KEY=${_API_KEY}'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/pdf-ocr-frontend:${BUILD_ID}'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/pdf-ocr-frontend:latest'
      - '-f'
      - 'Dockerfile'
      - '.'
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/pdf-ocr-frontend:${BUILD_ID}']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'pdf-ocr-frontend'
      - '--image'
      - 'gcr.io/${PROJECT_ID}/pdf-ocr-frontend:${BUILD_ID}'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--set-env-vars'
      - 'NEXT_PUBLIC_API_URL=${_API_URL},NEXT_PUBLIC_API_KEY=${_API_KEY}'

images:
  - 'gcr.io/${PROJECT_ID}/pdf-ocr-frontend:${BUILD_ID}'
  - 'gcr.io/${PROJECT_ID}/pdf-ocr-frontend:latest'

# Default substitutions - these are used if not overridden via --substitutions
# These MUST be set to your production backend URL and API key
substitutions:
  _API_URL: 'https://pdf-ocr-api-e3b7ctuuxa-uc.a.run.app'
  _API_KEY: 'M3CIlxn7kDnBSRy5OeDn1m36EkF1YTD9iaQqZiB02ys='

options:
  logging: CLOUD_LOGGING_ONLY
